### ISSUE TITLE
CFR_SUMMARY used twice instead of CFR_INSTRUCTIONS?

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#1]
Should be 
"**Summary:** [summary]\n
\n
**Abstract:** [abstract]\n
\n
**Instructions:** [instructions]\n"

But in this example it looks like Summary was used a second time instead of instructions

![image](https://cloud.githubusercontent.com/assets/1654485/8126422/aae9a3be-10ee-11e5-99ae-5f3a6beb07a0.png)

**Comment by teodorescuserban** [comment]
Fixed.
