### ISSUE TITLE
Resolve issue with default CFR license

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#10]
- [x] host license somewhere
- [ ] set license_other text for HDX

**Comment by teodorescuserban** [comment]
Please provide the texts required.

**Comment by teodorescuserban** [comment]
Please confirm that if the original license reads: 

```
"<p>See the site's <a href="/applications/data/page/terms-use">Terms of Use</a>.  This does not replace any terms of use information provided with the dataset.</p>
"
```

I should replace it with:

```
"See the site's [Terms of Use](/about/terms). This does not replace any terms of use information provided with the dataset."
```

**Comment by cjhendrix** [comment]
Let's make an adjustment to that based on the latest lawyerly input.  Please replace that string with

```
"See the site's [Terms of Use](http://www.humanitarianresponse.info/en/applications/data/page/terms-use). This does not replace any terms of use information provided with the dataset."
```

This basically keeps the orignal link working.  I suspect that will change before we have the first real run.

**Comment by teodorescuserban** [comment]
While license id and license title is dict based, it looks like license_other field will be displayed.

Fixed.
