### ISSUE TITLE
hrefs getting lost

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#11]
The source field contains an href (both in interface and as delivered by api).  We should be capturing these in HDX. 

![image](https://cloud.githubusercontent.com/assets/1654485/8128815/ef5f02fa-1102-11e5-920a-e37c0fd36ca2.png)

![image](https://cloud.githubusercontent.com/assets/1654485/8128824/08318370-1103-11e5-94a6-f10a0be4c875.png)

**Comment by teodorescuserban** [comment]
links are visible in the hdx api.
we are importing the links but are not showing them.
will investigate.

**Comment by teodorescuserban** [comment]
linked with #7

**Comment by cjhendrix** [comment]
I'm guessing we have to transform them to markup: `[text to hyperlink](http://url.to.link.to)`

**Comment by cjhendrix** [comment]
Let's discuss.  I propose the following HTML to Markup transformations:

```
html tag | number of occurrences | proposed transformation
<p>|4900|double new line
<p style= ... >|7|double new line (ignore style component)
<a href ... >|1607|[anchor text](URL)
<a class= ... >|6|[anchor text](URL)
<span class= ... >|136|ignore
<span style= ... >|66|ignore
<span>|108|ignore
<strong>|190|**text**
<ul>|38|double new line
<ol>|5|double new line
<li>|103|* (asterisk space)
<li style= ... >|2|* (asterisk space)
any header tag: <h1><h2> etc|3|double new line if not at the beginning of the field **text** double new line
<div>|77|double new line before and after the text
<div class= ... >|32|double new line before and after the text
<em>|118|*text*
<em style = . . . >|20|*text*
<br />|353|new line
<br style= . . . >|12|new line
<! -- ... >|1|ignore
ignore any other html tags
```

**Comment by teodorescuserban** [comment]
Would it be safe to assume that only the following fields will contain html?
1. abstract
2. data_sources
3. instructions
4. ~~label~~
5. recent_changes
6. summary
7. terms_of_use

Is there any other?

**Comment by cjhendrix** [comment]
I think there are no others, and "label" can't have markup (edited your comment above to reflect this).

**Comment by teodorescuserban** [comment]
Implemented 

```
<p>|4900|double new line
<p style= ... >|7|double new line (ignore style component)
<a href ... >|1607|[anchor text](URL)
<a class= ... >|6|[anchor text](URL)
```

all other html is ignored.
will add other exceptions once i return from ikea :)

**Comment by teodorescuserban** [comment]
hmh maybe not that good. suggestions?

http://test-data.hdx.rwlabs.org/dataset/mali-settlements

**Comment by cjhendrix** [comment]
Comments on the mali example you commented earlier:

![image](https://cloud.githubusercontent.com/assets/1654485/8179208/75477b4e-1415-11e5-98bd-0947c32b3a56.png)

**Comment by cjhendrix** [comment]
@teodorescuserban I've added a node to the mli intent file that has all the html formatting we want to process. 

It's node 105423.

And you can see the original looks here (you'll need to be logged in): https://www.humanitarianresponse.info/en/applications/data/datasets/locations/mali

**Comment by teodorescuserban** [comment]
@cjhendrix please check the result on http://test-data.hdx.rwlabs.org/dataset/mali-other

**Comment by teodorescuserban** [comment]
also check http://test-data.hdx.rwlabs.org/dataset/mali-settlements

**Comment by cjhendrix** [comment]
Looks good.  Made one issue based on the first one above.  

Can we also test against node 105423 as mentioned in my previous comment?

**Comment by teodorescuserban** [comment]
the node 105423 has already been migrated as http://test-data.hdx.rwlabs.org/dataset/mali-other

**Comment by cjhendrix** [comment]
I think it got overwritten by another one with the same name.  But I've changed the dataset category now so that it is unique.  If you run it again it should be ok.   Next week I should finally have time to get the repo updated and run these myself.

**Comment by teodorescuserban** [comment]
I refreshed the stag db with prod db and ran it again.
Please check it now:
http://test-data.hdx.rwlabs.org/dataset/mali-other-health
http://test-data.hdx.rwlabs.org/api/3/action/package_show?id=mali-other-health
Thank you.

It looks fixed.

**Comment by cjhendrix** [comment]
Looks great!  Now I'll switch that one back to just being "Other" so we can have a test of the duplicate names functionality.
