### ISSUE TITLE
What to do about html formatting of text

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#13]
This is a single field using html <ul> and <p> tags.  The html is retained, but not rendered.  Ideas?  Could we try converting some html to markup?  Or maybe it's better to deal with these manually. 

http://www.humanitarianresponse.info/en/operations/mali/dataset/mali-water-bodies-water-courses
![image](https://cloud.githubusercontent.com/assets/1654485/8129738/6cba0868-110c-11e5-99f2-3b1a9af87e8a.png)
https://test-data.hdx.rwlabs.org/dataset/mali-water-bodies-water-courses
![image](https://cloud.githubusercontent.com/assets/1654485/8129753/99a00d96-110c-11e5-9eaf-65a440c12e62.png)

**Comment by teodorescuserban** [comment]
linked with #7 and #11

**Comment by teodorescuserban** [comment]
closing. see #11
