### ISSUE TITLE
Could we pass authentication to HR to get unpublished datasets from the API

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#14]
Unpublished datasets on CFR will fail (logged as failure).  To be auto migrated, IMO would need to publish them at some point before the moment of migration and unpublish before HR.info scripts are run.

This could occur in the case of "publish only after a disaster" datasets or datasets that are previous versions than an office wants to keep around for archival purposes.  

We will explore passing authentication to HR.info to give access to unpublished datasets that require migration (presumably to private status).

**Comment by cjhendrix** [comment]
Correction, they are NOT logged as failures.  They have a fetch line in the log, but that's it.  Depending on our solution we will need to be sure we are logging this in a way that we don't loose them.

**Comment by teodorescuserban** [comment]
We explored the HR auth and proven to be too cumbersome. We will just rely on manually logging in to HR info site, then manually copy the SESS cookie from there and pass it on our script to be able to view a private dataset.
Closing.

**Comment by cjhendrix** [comment]
https://www.youtube.com/watch?v=Ty89giMsSWE
