### ISSUE TITLE
Implement checks to see if download of google docs succeeds.

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/cod-migration#15]
When someone changes the permissions of a config, intent or taxonomy google doc file, it is possible that downloading the csv version of it is impossible without login.

We need to detect this situation and display nicely to the user that is running the script.

**Comment by cjhendrix** [comment]
Low priority, since there are now only a couple of us who can change those permissions.  And I've been educated properly.  :)

**Comment by teodorescuserban** [comment]
Fixed.

I am trying to download the files in 2 different URLs.
If both give html content i will exit.
If one of them gives csv I raise `KeyError('get gdoc', filename)`
