### ISSUE TITLE
Missing source in HDX

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#3]
For node 4537, the HDX Source is "Unknown" but should be "The population data was sourced from the Islamic Republic of Afghanistan Central Statistics Organization (CSO)."
https://test-data.hdx.rwlabs.org/dataset/afghanistan-population-statistics

Other datasets have a value in Source.  For example: https://test-data.hdx.rwlabs.org/dataset/mali-settlements

**Comment by teodorescuserban** [comment]
Fixed.
