### ISSUE TITLE
Bug introduced by migration-incomplete tag

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/cod-migration#34]
Please test it, identify it and correct it.

**Comment by teodorescuserban** [comment]
Upon dataset and resources success, the log file contains 2 `update` lined but no "datset";

the last one should be "ViCTORY"

**Comment by cjhendrix** [comment]
Vicotry.  I like it.

**Comment by cjhendrix** [comment]
But Guillaume's script is expected COMPLETED (or whatever it was before)

**Comment by teodorescuserban** [comment]
I might have been a little sleepy :)

**Comment by teodorescuserban** [comment]
Ok so actually, the bug consist in a duplicate line with "update: true" instead of the "COMPLETE" or "NOMIGRATE"

**Comment by teodorescuserban** [comment]
fixed.
