### ISSUE TITLE
Have the file size in resource description

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/cod-migration#38]
@cjhendrix needs to get approval for this.

**Comment by teodorescuserban** [comment]
related to #37

**Comment by teodorescuserban** [comment]
Any news on that, @cjhendrix ?

**Comment by cjhendrix** [comment]
We should wait for it to be displayed in the interface (https://github.com/OCHA-DAP/hdx-ckan/issues/2612). Because we are storing the file size in anticipation of it being used in the interface, I'm going to close this one.
