### ISSUE TITLE
We are altering the names of files

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#40]
The resource title and the name of the actual downloaded file do not match.  Happy to discuss options.

![image](https://cloud.githubusercontent.com/assets/1654485/8618731/21944964-2711-11e5-892e-0eeb4bf3826d.png)

**Comment by teodorescuserban** [comment]
It seems this is also related to our ckan 2.3 ofs migration.
tagging @danmihaila and @alexandru-m-g 

@cjhendrix , you can test as follows:
1. download the resource highlighted by you and change the file name locally to be like the name on ckan (with the underscores)
2. remove the resource from the dataset
3. create a new resource on the dataset from the UI and upload the renamed file.

You will get a resource that, on download, will have it's file name changed.

I suggest to open a related issue on hdx-ckan.

**Comment by cjhendrix** [comment]
Closing this one.

**Comment by cjhendrix** [comment]
See https://github.com/OCHA-DAP/hdx-ckan/issues/3318
