### ISSUE TITLE
Date slippage

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#41]
Dataset date is off by one day in node 4536: 
https://test-data.hdx.rwlabs.org/dataset/afghanistan-water-courses
https://www.humanitarianresponse.info/en/operations/afghanistan/dataset/afghanistan-water-courses

**Comment by teodorescuserban** [comment]
might be the timezone differences. will check it out later.

**Comment by cjhendrix** [comment]
We have to be careful without because we don't want to unintentionally change the year on a dataset marked as 31-Dec or 1-Jan.

**Comment by cjhendrix** [comment]
Strange.   It seems the HRinfo API sometimes delivers a different date (by a day or two) than the API.  HDX uses the API and this seems to be more accurate. 

We should just confirm that we are accurately reproducing the date that the API delivers.   If so, we can close.

**Comment by cjhendrix** [comment]
I just reran and checked the original dataset that had this problem (on feature) and it seems to be ok.  Closing this one and will keep checking dates as we test.
