### ISSUE TITLE
Dataset should be private

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#42]
The intent file indicates private for node 4536 but it ends up as public.

https://test-data.hdx.rwlabs.org/dataset/afghanistan-water-courses
https://www.humanitarianresponse.info/en/operations/afghanistan/dataset/afghanistan-water-courses

**Comment by teodorescuserban** [comment]
Fixed.
It appeared the privacy setting didn't make it all the way to the dataset update method :)

Please note that I took the opportunity to change the code so that for the short tests any dataset will be made private - meaning we can also test on prod :dancer:

**Comment by cjhendrix** [comment]
Good idea!
