### ISSUE TITLE
Multilingual terms of use

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#44]
There are different language versions of the terms of use (depending on the language setting of the hr.info space).   French and Spanish are the only other ones as far as I know.  

Just as we do with the english version of CFR's default terms of use, we need to transform the French and Spanish as well.   We will transform them to **english**.  

Issue #10 and #43 have more info about how we are handling for english.

For this issue
Add a handler for the string below with the same output as for english.  I'll add the spanish string here as soon as I find an example. 

```
terms_of_use: "<p>Prier de voir les<a href="/applications/data/page/terms-use">Conditions d’utilisation</a> de ce site. Cela ne remplace pas les conditions d’utilisation liées à ces données.</p> "
```

**Comment by teodorescuserban** [comment]
What do we do here, @cjhendrix ?

**Comment by cjhendrix** [comment]
Let's add a handler for this key:value: 

```
terms_of_use: "<p>Prier de voir les<a href="/applications/data/page/terms-use">Conditions d’utilisation</a> de ce site. Cela ne remplace pas les conditions d’utilisation liées à ces données.</p> "
```

We will need to replace the URL with the same one we will use for english (as described here https://github.com/OCHA-DAP/hdx-ckan/issues/3055 )

Note that there is a space missing in the above terms of use and the language needs to change a little, so let's replace it with 

```
terms_of_use: "<p>Prier de voir les <a href="our HDX URL here">Conditions d’utilisation</a>. Cela ne remplace pas les conditions d’utilisation liées à ces données.</p> "
```

**Comment by teodorescuserban** [comment]
Working tomorrow on OCHA-DAP/hdx-ckan#3055

**Comment by cjhendrix** [comment]
Unless we find a spanish example, this is done.  Closing.
