### ISSUE TITLE
Often unable to create resources

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#45]
Trying to run gospawn for the first time since Friday.  Getting this error on many resources (but not all):

Uploading resource resources/afg_ppl_settlements_pnt_cso.zip
FAILED.
{"help": "http://test-data.hdx.rwlabs.org/api/3/action/help_show?name=resource_create", "success": false, "error": {"url": ["Missing value"], "__type": "Validation Error"}}
Error occured when create : False

However even with the dataset registers as complete, there are no resources.  For example: https://test-data.hdx.rwlabs.org/dataset/afghanistan-elevation-model

**Comment by teodorescuserban** [comment]
This exact validation seems to appear once we updated to ckan 2.3
I solved this a few days ago by adding an empty `url` field when uploading a new resource.
Ckan will take care of that field by adding the right, actual, url.
