### ISSUE TITLE
Strip out tabs from free text fields

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#48]
We don't allow tabs to be entered via the interface, but they seem to sneak in through the API.  Markdown is interpreting them as code (or something like that):

![image](https://cloud.githubusercontent.com/assets/1654485/9039472/f6ed8984-39fb-11e5-9192-7e42bfabd694.png)

Could we simply strip them out as part of the processing you are already doing on free text?

**Comment by cjhendrix** [comment]
Actually, in the CFR api it doesn't look like there are tabs there.  But I could see them in the edit view on this dataset (since modified).   

Here is the api link: https://www.humanitarianresponse.info/en/api/v1.0/datasets/90424

**Comment by cjhendrix** [comment]
This dataset still has the tabs in description.  Edit the dataset to see them. https://test-data.hdx.rwlabs.org/dataset/edit/central-african-republic-elevation-model-0

**Comment by cjhendrix** [comment]
Another example: https://test-data.hdx.rwlabs.org/dataset/central-african-republic-admin-boundaries.  

No tabs visible in the CFR API output, so I think our conversion must be creating them somehow.

**Comment by teodorescuserban** [comment]
This one _does_ have tabs in `abstract` https://www.humanitarianresponse.info/en/api/v1.0/datasets/90424

**Comment by teodorescuserban** [comment]
Fixed.
Please see:
https://test-data.hdx.rwlabs.org/dataset/central-african-republic-admin-boundaries
https://test-data.hdx.rwlabs.org/dataset/central-african-republic-elevation-model-0
https://test-data.hdx.rwlabs.org/dataset/central-african-republic-elevation-model
