### ISSUE TITLE
Bulleted or numbered list need at least 1 blank line above to be correctly rendered

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#49]
https://www.humanitarianresponse.info/en/operations/central-african-republic/dataset/central-african-republic-admin-level-0-international
![image](https://cloud.githubusercontent.com/assets/1654485/9041948/8f31a518-3a0b-11e5-8bcd-f1ef4ac8f293.png)

https://test-data.hdx.rwlabs.org/dataset/central-african-republic-admin-boundaries
![image](https://cloud.githubusercontent.com/assets/1654485/9041951/9c3734ee-3a0b-11e5-954b-657f3bf46fa9.png)

**Comment by teodorescuserban** [comment]
Fixed.
