### ISSUE TITLE
Failing on this dataset, maybe because it has category = COD

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#50]
https://www.humanitarianresponse.info/en/operations/central-african-republic/dataset/central-african-republic-other-cod

We could ignore category = COD or FOD when there is more than one category.  And if category is only COD or FOD, we could NOMIGRATE-CATEGORY

**Comment by teodorescuserban** [comment]
Example of dataset with only COD or FOD as categories?  (For testing)

**Comment by teodorescuserban** [comment]
Closed.

**Comment by cjhendrix** [comment]
I have found only one example with **only** category  = cod,fod, but it is multicountry and so doesn't migrate anyway.
