### ISSUE TITLE
Change migration-incomplete tag to something less scary in the activity stream

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#52]
In a successful migration, the most recent activity stream will be:
![image](https://cloud.githubusercontent.com/assets/1654485/9086816/1b3280ba-3b87-11e5-8b3d-2af9120c205e.png)

That may generate some questions from IMOs.  Let's change the tag to "migration-processing".

**Comment by teodorescuserban** [comment]
Closing.
