### ISSUE TITLE
Change the text replacement for multiple admin boundaries

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#53]
The current replacement text is "Admin Boundaries".  Let's change that to "Administrative Boundaries"

We may make a similar change  in the taxonomy for "Admin Level 1 Boundaries", etc.  We had originally kept them short so that the titles wouldn't get too long, but now that we are replacing mulitples, we have more space.

**Comment by teodorescuserban** [comment]
Changed.
