### ISSUE TITLE
Not all datasets should get COD tag

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#54]
It seems that all migrated datasets are getting the COD tag.  However, there are some that should not.

See the taxonomy: https://docs.google.com/spreadsheets/d/1dW-inh8SPhTvFay21xjleMdC78yf_g4uhOytNi4dATo/edit#gid=0

Examples: http://feature-data.hdx.rwlabs.org/dataset/indonesia-other
http://feature-data.hdx.rwlabs.org/dataset/central-african-republic-security

**Comment by teodorescuserban** [comment]
Fixed.
