### ISSUE TITLE
Combination of bold and href breaks links in markdown conversion

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#55]
http://feature-data.hdx.rwlabs.org/dataset/east-timor-admin-level-2-boundaries

CRF: https://www.humanitarianresponse.info/en/api/v1.0/datasets/4328

This was converted to `**Full Metadata**(http://www.pdc.org/mde/full_metadata.jsp?docId={A8E20F47-7249-4787-B9D2-502E5D465BB4}&loggedIn=false)`

But should have been `[**Full Metadata**](http://www.pdc.org/mde/full_metadata.jsp?docId={A8E20F47-7249-4787-B9D2-502E5D465BB4}&loggedIn=false)`

![image](https://cloud.githubusercontent.com/assets/1654485/9110068/f7932ca4-3c3a-11e5-9910-ae1b57f568bc.png)

**Comment by teodorescuserban** [comment]
Fixed.
