### ISSUE TITLE
Handle blank lines in intent file

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#57]
An intent file might have "blank" lines (no node id).  These should be skipped.  No logging necessary (but it is ok to log)

My most recent run on feature had some empty lines at the bottom and for each one, the script updated this dataset: http://feature-data.hdx.rwlabs.org/dataset/kyrgyzstan-admin-level-2-boundaries

Interestingly, that dataset is not in either of the intent files being used!

**Comment by teodorescuserban** [comment]
I will fix it soon.

**Comment by teodorescuserban** [comment]
Fixed. Closing.
