### ISSUE TITLE
Uploading large files hangs

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#58]
We've had this one for a few days.  I've seen it on files 59MB, 64MB, and 39MB.    ZIP and RAR.
Terminal output looks like:

```
Start processing dataset with Node ID = 90424
Dataset exists.
Identifying dataset: central-african-republic-elevation-model
Updating identified existing dataset: central-african-republic-elevation-model
Trying to get resources/srtm_40.rar
Uploading resource resources/srtm_40.rar
```

```
Start processing dataset with Node ID = 4403
Creating new dataset: cote-d-ivoire-water-courses
Trying to get resources/cours_deau.zip
Uploading resource resources/cours_deau.zip
```

**Comment by cjhendrix** [comment]
Just saw a 16MB work ok.

**Comment by cjhendrix** [comment]
This doesn't seem to be happening on feature (as of last night).

**Comment by teodorescuserban** [comment]
It looks like there is a misconfig of frontend nginx managed by our provider.
They will soon increase the `client_max_body_size` parameter to 1GB.
I will close after this is resolved.

**Comment by teodorescuserban** [comment]
Fixed by Zack from P2 on their nginx
