### ISSUE TITLE
Problem processing accented characters in country name?

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#60]
gospawn is failing (terminal output below) on datasets for Côte d'Ivoire.  

I haven't run into this before, so I am tempted to think it is because of my switch today to running gospawn from windows rather than ubuntu.  

I have pushed the config key and test node ids to the repo.  Could you please pull and try running test short?  If it works for you I know it's something in windows python.

**Comment by teodorescuserban** [comment]
where is the terminal output?

**Comment by teodorescuserban** [comment]
In call with @cjhendrix we came to the conclusion that the culprit is python on windows.
