### ISSUE TITLE
Loading intent file fails for this one

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#61]
I can't figure out why it's failing on the AFG intent file (this is the real one, created by Godfrey and could be modified by the IMO any time, so we need to be careful with it).

https://docs.google.com/spreadsheets/d/1eTFd48aaiLs1tknNn9c6u_4ngisCcsbaDlTVZX9MVJQ/edit#gid=0

**Comment by teodorescuserban** [comment]
@cjhendrix  log?

**Comment by teodorescuserban** [comment]
funny char in intent file.
possible fix: getting only the interesting fields from csv.

**Comment by teodorescuserban** [comment]
In call with @cjhendrix we came to the conclusion that the culprit is python on windows.
