### ISSUE TITLE
Name collision problem?

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#62]
CJ to investigate further . . .

Node 5016

Dataset exists.
Identifying dataset: central-african-republic-other
Changing the dataset name to avoid name collisions...
Dataset exists.
Identifying dataset: central-african-republic-other-0
Changing the dataset name to avoid name collisions...
Dataset exists.
Identifying dataset: central-african-republic-other-0-0
Changing the dataset name to avoid name collisions...
Dataset exists.
Identifying dataset: central-african-republic-other-0-0-0
Changing the dataset name to avoid name collisions...
Dataset exists.
Identifying dataset: central-african-republic-other-0-0-0-0
Changing the dataset name to avoid name collisions...
Dataset exists.
Identifying dataset: central-african-republic-other-0-0-0-0-0
Changing the dataset name to avoid name collisions...
Creating new dataset: central-african-republic-other-0-0-0-0-0-0

**Comment by teodorescuserban** [comment]
Working for me on testing.

serban@pinkBox:~/Projects/HDX/hdx-gospawn$ python3 gospawn.py test short
Trying to get configs/intent.csv
SUCCESS.
Trying to get configs/intent.csv
SUCCESS.
Start processing dataset with Node ID = 5016
Creating new dataset: central-african-republic-other
Dataset exists.
Dataset with Node ID = 5016 has been MIGRATED.

**Comment by cjhendrix** [comment]
Not an issue.  CAR has made everything "Other" so you get lots of duplicate titles.
