### ISSUE TITLE
Capitalization in country title component not respected

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#63]
The capitalization should match the taxonomy file (HDX_TITLE_SLUG).

![image](https://cloud.githubusercontent.com/assets/1654485/9201256/4c6fa620-404c-11e5-8c23-50900ac717b4.png)

**Comment by teodorescuserban** [comment]
That is arguably the hardest to do.
Because right now I am lowering all chars and title them up for the title.
If I am not lowering them, I am at the mercy of HR info source to get a proper name :)

**Comment by teodorescuserban** [comment]
Ignore my last comment.
Fixed.
