### ISSUE TITLE
HREF conversion broken by something about this particular configuration

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#65]
![image](https://cloud.githubusercontent.com/assets/1654485/9224941/7c63219e-4106-11e5-9a94-37530d387992.png)

Node id 4335

https://feature-data.hdx.rwlabs.org/dataset/somalia-population-statistics

**Comment by teodorescuserban** [comment]
The source text reads:

`<a href="http://www.fsnau.org/downloads/Total%20Population%20in%20AFLC%2C%20HE%20and%20Famine%20in%20Somalia.pdf">Total population in Acute Food and Livelihood Crisis, Humanitarian Emergency and Famine in Somalia <span class="ext">along with baseline population </span>by region [FSNAU] (PDF, 49KB)</a>`

The markdwon expects the label for the link to be enclosed by square brackets but [FSNAU] inside the label breaks that.

Any suggestions?

**Comment by teodorescuserban** [comment]
I can replace square brackets with parentheses inside the label text.
Green?

**Comment by cjhendrix** [comment]
Yes.  I've checked the full dataset list and square brackets occur 18 times.  I didn't see anywhere that it would be problematic to change them to parentheses and several places where it will be problematic if we don't.

**Comment by teodorescuserban** [comment]
Ok.
I will change it then.

**Comment by teodorescuserban** [comment]
Fixed.
