### ISSUE TITLE
Additional logic for handling license

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/cod-migration#75]
We want to change the way we migrate the licenses that we currently leave untouched (all strings other than default license string).  In those cases we want to append `\n\n [default string]`

![image](https://cloud.githubusercontent.com/assets/1654485/9851120/626dc2c0-5af7-11e5-955c-134b44698ffa.png)

**Comment by teodorescuserban** [comment]
How do I decide which default language for the default string?
Right now it appears we are only using English.

**Comment by teodorescuserban** [comment]
Should I fix that too?

**Comment by teodorescuserban** [comment]
Oh, a reminder: we don't have the text for Spanish default license, so only en and fr available.

**Comment by teodorescuserban** [comment]
Closing.
Please note the default string will be only in English.

**Comment by cjhendrix** [comment]
Understood re Spanish.  Por favor por favor.  :)  And we are only using english in the output, so all good.
