### ISSUE TITLE
Potential problems on Phase 2

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/cod-migration#79]
The datasets already migrated in Phase 1 are changed on HR.info.
One of the changes is that the resources list is gone.
The HDX migration process overwrites the dataset altogether (does patch anything at the moment).

As a result, IF we try to migrate again a dataset that has been flagged on HR.info as migrated, we will end up on HDX with an incomplete dataset with no resources.

Example here: [HR.info api](https://www.humanitarianresponse.info/en/api/v1.0/datasets/68739) and [HDX test](https://test-data.hdx.rwlabs.org/dataset/cape-verde-administrative-boundaries).

**We have to be very careful!**

**Comment by teodorescuserban** [comment]
After a talk with @cjhendrix we decided to look for a specific string in the summary of the HR dataset.
An example of a summary field would be:

```
"<p>This dataset is now maintained on the <a href="https://data.hdx.rwlabs.org/dataset/cape-verde-administrative-boundaries">Humanitarian Data Exchange</a>.</p>"
```

**Comment by cjhendrix** [comment]
Tested and working.  This was an awesome catch, @teodorescuserban
