### ISSUE TITLE
2 resources missing after phase 2 of COD import

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/cod-migration#86]
@teodorescuserban  and I checked how many resources were imported in this phase on prod: 409.
In the gospawn log we see there were 411 resources processed. So it seems like only 2 resources are missing.

Agreed upon steps before next phase:
1.  After the import of each dataset is finished, there should be a check to see that the number of resources that now exist in CKAN is correct ( and log if there is a discrepancy )
2.  Using patch instead of update to update the resource or dataset

pinging @cjhendrix

**Comment by danmihaila** [comment]
Maybe 2 have filename containing special characters
